<?php
declare(strict_types=1);
require_once __DIR__.'/server/IntercomState.php';
const STATE_FILE=__DIR__.'/data/state.json';const SIGNAL_FILE=__DIR__.'/data/signals.json';const SESSION_MAX=80;
$adminCode=getenv('TEDX_INTERCOM_ADMIN_CODE')?:'';
header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store');header('X-Content-Type-Options:nosniff');
function out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function input():array{$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function initFiles():void{if(!is_dir(dirname(STATE_FILE)))mkdir(dirname(STATE_FILE),0775,true);if(!file_exists(STATE_FILE))file_put_contents(STATE_FILE,json_encode(IntercomState::initialState(),JSON_UNESCAPED_UNICODE),LOCK_EX);if(!file_exists(SIGNAL_FILE))file_put_contents(SIGNAL_FILE,'[]',LOCK_EX);}
function sid(array $d):string{$id=trim((string)($d['sessionId']??''));if($id===''||strlen($id)>SESSION_MAX)out(['ok'=>false,'error'=>'SESSION_REQUIRED'],400);return $id;}
function clean(array &$s):void{IntercomState::cleanup($s,time());}
function stateWrite(callable $fn):mixed{initFiles();$h=fopen(STATE_FILE,'c+');if(!$h)out(['ok'=>false,'error'=>'STATE_OPEN_FAILED'],500);flock($h,LOCK_EX);rewind($h);$s=json_decode(stream_get_contents($h)?:'',true);if(!is_array($s))$s=IntercomState::initialState();$r=$fn($s);if(isset($r['state'])){rewind($h);ftruncate($h,0);fwrite($h,json_encode($r['state'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));fflush($h);}flock($h,LOCK_UN);fclose($h);return $r;}
function stateRead():array{initFiles();$h=fopen(STATE_FILE,'r');flock($h,LOCK_SH);$s=json_decode(stream_get_contents($h)?:'',true);flock($h,LOCK_UN);fclose($h);return is_array($s)?$s:IntercomState::initialState();}
function signals(callable $fn):mixed{initFiles();$h=fopen(SIGNAL_FILE,'c+');flock($h,LOCK_EX);rewind($h);$s=json_decode(stream_get_contents($h)?:'[]',true);if(!is_array($s))$s=[];$r=$fn($s);if(isset($r['signals'])){rewind($h);ftruncate($h,0);fwrite($h,json_encode($r['signals'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));fflush($h);}flock($h,LOCK_UN);fclose($h);return $r;}
function adminOk(string $code):bool{return $GLOBALS['adminCode']!==''&&hash_equals($GLOBALS['adminCode'],$code);}
$m=$_SERVER['REQUEST_METHOD'];$d=$m==='GET'?$_GET:input();$op=(string)($d['op']??'');
try{
if($m==='GET'&&$op==='health')out(['ok'=>true,'service'=>'tedx-intercom','time'=>gmdate('c')]);
if($m==='GET'&&$op==='state')out(['ok'=>true,'state'=>IntercomState::publicState(stateRead())]);
if($m==='POST'&&$op==='join'){$id=sid($d);$r=stateWrite(function(array $s)use($d,$id){clean($s);$ch=(string)($d['channelId']??'main');if(!IntercomState::channelExists($s,$ch))$ch='main';$role=(($d['role']??'member')==='admin'&&adminOk((string)($d['adminCode']??'')))?'admin':'member';IntercomState::upsertParticipant($s,$id,(string)($d['name']??''),$role,$ch,time());return['state'=>$s,'role'=>$role];});out(['ok'=>true,'role'=>$r['role'],'state'=>IntercomState::publicState($r['state'])]);}
if($m==='POST'&&$op==='heartbeat'){$id=sid($d);stateWrite(function(array $s)use($id){clean($s);IntercomState::touch($s,$id,time());return['state'=>$s];});out(['ok'=>true]);}
if($m==='POST'&&$op==='take'){$id=sid($d);$r=stateWrite(function(array $s)use($id){clean($s);$p=IntercomState::participant($s,$id);if(!$p)return['state'=>$s,'ok'=>false,'error'=>'NOT_JOINED'];$c=IntercomState::channel($s,$p['channelId']);$a=$c['active']??null;if($a&&$a['sessionId']!==$id&&$p['role']!=='admin')return['state'=>$s,'ok'=>false,'error'=>'CHANNEL_BUSY','active'=>$a];if($a&&$a['sessionId']===$id)return['state'=>$s,'ok'=>true,'active'=>$a];$a=IntercomState::startSpeaking($c,$p,time());$c['active']=$a;IntercomState::replaceChannel($s,$c);return['state'=>$s,'ok'=>true,'active'=>$a];});out(['ok'=>$r['ok'],'error'=>$r['error']??null,'active'=>$r['active']??null]);}
if($m==='POST'&&$op==='release'){$id=sid($d);$r=stateWrite(function(array $s)use($id){clean($s);$p=IntercomState::participant($s,$id);if(!$p)return['state'=>$s,'ok'=>false,'error'=>'NOT_JOINED'];$c=IntercomState::channel($s,$p['channelId']);if(($c['active']['sessionId']??null)===$id){IntercomState::stopSpeaking($c);IntercomState::replaceChannel($s,$c);}return['state'=>$s,'ok'=>true];});out(['ok'=>$r['ok']]);}
if($m==='POST'&&$op==='request'){$id=sid($d);$r=stateWrite(function(array $s)use($id){clean($s);$p=IntercomState::participant($s,$id);if(!$p)return['state'=>$s,'ok'=>false,'error'=>'NOT_JOINED'];$c=IntercomState::channel($s,$p['channelId']);if(!$c['active'])return['state'=>$s,'ok'=>false,'error'=>'CHANNEL_FREE'];IntercomState::requestSpeak($c,$p,time());IntercomState::replaceChannel($s,$c);return['state'=>$s,'ok'=>true];});out(['ok'=>$r['ok'],'error'=>$r['error']??null]);}
if($m==='POST'&&$op==='createChannel'){$id=sid($d);$r=stateWrite(function(array $s)use($d,$id){clean($s);$p=IntercomState::participant($s,$id);if(($p['role']??'member')!=='admin')return['state'=>$s,'ok'=>false,'error'=>'ADMIN_REQUIRED'];$x=IntercomState::createChannel($s,(string)($d['name']??''),$id,time());return['state'=>$s,'ok'=>$x['ok'],'channel'=>$x['channel']??null,'error'=>$x['error']??null];});out(['ok'=>$r['ok'],'channel'=>$r['channel']??null,'error'=>$r['error']??null]);}
if($m==='POST'&&$op==='deleteChannel'){$id=sid($d);$r=stateWrite(function(array $s)use($d,$id){clean($s);$p=IntercomState::participant($s,$id);if(($p['role']??'member')!=='admin')return['state'=>$s,'ok'=>false,'error'=>'ADMIN_REQUIRED'];$x=IntercomState::deleteChannel($s,(string)($d['channelId']??''));return['state'=>$s,'ok'=>$x['ok'],'error'=>$x['error']??null];});out(['ok'=>$r['ok'],'error'=>$r['error']??null]);}
if($m==='GET'&&$op==='signals'){$id=sid($d);$r=signals(function(array $a)use($id){$now=time();$keep=[];$mine=[];foreach($a as $x){if(($x['expiresAt']??0)<=$now)continue;if(($x['to']??'')===$id)$mine[]=$x;else $keep[]=$x;}return['signals'=>$keep,'mine'=>$mine];});out(['ok'=>true,'signals'=>$r['mine']]);}
if($m==='POST'&&$op==='signal'){$id=sid($d);$type=(string)($d['type']??'');$to=trim((string)($d['to']??''));$ch=trim((string)($d['channelId']??''));$ep=trim((string)($d['epoch']??''));if(!in_array($type,['offer','answer'],true)||$to===''||$ch===''||$ep==='')out(['ok'=>false,'error'=>'BAD_SIGNAL'],400);$r=stateWrite(function(array $s)use($id,$to,$type,$ch,$ep){clean($s);$from=IntercomState::participant($s,$id);$target=IntercomState::participant($s,$to);$c=IntercomState::channel($s,$ch);if(!$from||!$target||$from['channelId']!==$ch||$target['channelId']!==$ch)return['state'=>$s,'ok'=>false,'error'=>'SIGNAL_PARTICIPANT_MISMATCH'];if(!$c||!$c['active'])return['state'=>$s,'ok'=>false,'error'=>'NO_ACTIVE_SPEAKER'];if(($type==='offer'&&$id!==$c['active']['sessionId'])||($type==='answer'&&$to!==$c['active']['sessionId'])||$ep!==$c['active']['epoch'])return['state'=>$s,'ok'=>false,'error'=>'INVALID_SIGNAL'];return['state'=>$s,'ok'=>true];});if(!$r['ok'])out(['ok'=>false,'error'=>$r['error']],409);signals(function(array $a)use($d,$id,$to,$type,$ch,$ep){$a[]=['id'=>bin2hex(random_bytes(8)),'to'=>$to,'from'=>$id,'type'=>$type,'channelId'=>$ch,'epoch'=>$ep,'payload'=>$d['payload']??null,'expiresAt'=>time()+20];return['signals'=>$a];});out(['ok'=>true]);}
out(['ok'=>false,'error'=>'UNKNOWN_OPERATION'],404);
}catch(Throwable $e){error_log((string)$e);out(['ok'=>false,'error'=>'SERVER_ERROR'],500);}