const $=id=>document.getElementById(id),API='api.php';
const S={id:localStorage.tedxId||(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)),name:'',role:'member',adminCode:'',ch:'main',server:null,stream:null,speaking:false,peer:null,peers:new Map(),poll:null,sig:null,beat:null,deferred:null,requested:false,lastSpeaker:null};
localStorage.tedxId=S.id;
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=m=>{const x=document.createElement('div');x.className='toast';x.textContent=m;$('toasts').append(x);setTimeout(()=>x.remove(),3000)};
async function api(method,op,data={}){let u=API+'?op='+encodeURIComponent(op);const o={method:method,headers:{'Content-Type':'application/json','Cache-Control':'no-cache'}};if(method==='GET')u+='&'+new URLSearchParams(data).toString();else o.body=JSON.stringify(Object.assign({op:op},data));const r=await fetch(u,o),j=await r.json();if(!r.ok||j.ok===false){const e=new Error(j.error||'HTTP_'+r.status);e.data=j;throw e}return j}
function active(){return S.server&&S.server.channels?S.server.channels[S.ch]:null}
function status(t){$('conn').textContent=t}
async function askNotif(){if(!('Notification'in window))return;$('notif').textContent=await Notification.requestPermission()}
async function localNotify(){if(!('Notification'in window)||Notification.permission!=='granted')return;try{const r=await navigator.serviceWorker.ready;await r.showNotification('Konuşma başladı',{body:(active().active.name||'Ekip üyesi')+' konuşuyor.',icon:'/icons/icon.svg',tag:'tedx-intercom-speaker',renotify:true})}catch{}}
async function micPermission(){try{const t=await navigator.mediaDevices.getUserMedia({audio:true});t.getTracks().forEach(x=>x.stop());$('mic').textContent='Hazır'}catch{$('mic').textContent='İzin verilmedi'}}
async function getMic(){const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});S.stream=s;s.getAudioTracks().forEach(t=>t.enabled=false)}
async function load(){try{const r=await api('GET','state');const prev=active();S.server=r.state;const c=active();render();status('Bağlı');if(c&&c.active&&(!prev||!prev.active||prev.active.sessionId!==c.active.sessionId)&&c.active.sessionId!==S.id)localNotify()}catch{status('Bağlantı yok')}}
function render(){let c=active();if(!c){S.ch='main';c=active()}$('channelName').textContent=c.name;const mem=Object.values(S.server.participants||{}).filter(p=>p.channelId===S.ch);$('meta').textContent=mem.length+' kişi • '+(c.permanent?'Ana kanal':'Özel kanal');$('channels').innerHTML=Object.values(S.server.channels).map(x=>'<button class="channel '+(x.id===S.ch?'on':'')+'" data-ch="'+esc(x.id)+'">'+esc(x.name)+(x.active?' ●':'')+'</button>').join('');document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>switchChannel(b.dataset.ch));$('count').textContent=mem.length;$('members').innerHTML=mem.map(p=>'<span class="member '+(c.active&&p.sessionId===c.active.sessionId?'active':'')+'">'+esc(p.name)+(p.role==='admin'?' • Y':'')+'</span>').join('');$('speaker').textContent=c.active?c.active.name:'Kanal boş';$('timer').textContent=c.active?Math.floor(Math.max(0,c.active.expiresAt-Math.floor(Date.now()/1000))/60)+':'+String(Math.max(0,c.active.expiresAt-Math.floor(Date.now()/1000))%60).padStart(2,'0'):'—';$('ptt').classList.toggle('busy',!!c.active&&c.active.sessionId!==S.id);$('request').disabled=!(c.active&&c.active.sessionId!==S.id);$('request').classList.toggle('on',S.requested);$('request').textContent=S.requested?'Sıra İstendi ✓':'Sıra İste';document.querySelectorAll('.admin').forEach(x=>x.classList.toggle('hide',S.role!=='admin'));$('queue').classList.toggle('hide',S.role!=='admin');$('deleteChannel').classList.toggle('hide',S.ch==='main'||S.role!=='admin');$('qCount').textContent=(c.requests||[]).length;$('requests').innerHTML=(c.requests||[]).map(x=>'<div class="requestRow">'+esc(x.name)+'<span>bekliyor</span></div>').join('');$('identity').innerHTML='<b>'+esc(S.name)+'</b><br><small>'+(S.role==='admin'?'Yönetici':'Ekip Üyesi')+'</small>'}
async function join(){await api('POST','join',{sessionId:S.id,name:S.name,role:S.role,adminCode:S.adminCode,channelId:S.ch});await load();$('join').classList.add('hide');$('radio').classList.remove('hide');if(!S.beat)S.beat=setInterval(()=>api('POST','heartbeat',{sessionId:S.id}).catch(()=>status('Bağlantı yok')),7000);if(!S.poll)S.poll=setInterval(load,900);if(!S.sig)S.sig=setInterval(pollSignals,700)}
async function switchChannel(ch){if(S.speaking)await stopTalk();S.ch=ch;S.requested=false;stopPeers();await join()}
async function startTalk(){if(S.speaking)return;const c=active();if(c&&c.active&&c.active.sessionId!==S.id)return toast(c.active.name+' konuşuyor.');try{const x=await api('POST','take',{sessionId:S.id});if(x.ok===false)return toast(x.error||'PTT alınamadı');if(!S.stream)await getMic();S.server.channels[S.ch].active=x.active;S.speaking=true;S.stream.getAudioTracks().forEach(t=>t.enabled=true);$('ptt').classList.add('talking');$('ptt').firstChild.textContent='KONUŞUYORSUN';await makePeers();setTimeout(()=>{if(S.speaking)stopTalk(true)},180000)}catch(e){toast(e.message)}}
async function stopTalk(max){if(!S.speaking)return;S.speaking=false;if(S.stream){S.stream.getAudioTracks().forEach(t=>t.enabled=false);S.stream.getTracks().forEach(t=>t.stop());S.stream=null}$('ptt').classList.remove('talking');$('ptt').firstChild.textContent='BASILI TUT';stopPeers();await api('POST','release',{sessionId:S.id}).catch(()=>{});if(max)toast('3 dakika doldu; tekrar konuşabilirsin.');await load()}
function stopPeers(){for(const p of S.peers.values())p.close();S.peers.clear();if(S.peer){S.peer.close();S.peer=null}}
async function makePeers(){const c=active();if(!c||!c.active||!S.stream)return;const ep=c.active.epoch,ls=Object.values(S.server.participants||{}).filter(p=>p.channelId===S.ch&&p.sessionId!==S.id);await Promise.allSettled(ls.map(p=>makePeer(p.sessionId,ep)))}
async function makePeer(id,ep){if(S.peers.has(id))return;const pc=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun.cloudflare.com:3478']} ]});S.peers.set(id,pc);S.stream.getTracks().forEach(t=>pc.addTrack(t,S.stream));pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){pc.close();S.peers.delete(id)}};try{const o=await pc.createOffer();await pc.setLocalDescription(o);await gather(pc);await api('POST','signal',{sessionId:S.id,to:id,type:'offer',channelId:S.ch,epoch:ep,payload:{sdp:pc.localDescription}})}catch{pc.close();S.peers.delete(id)}}
async function handleSignal(x){const c=active();if(!c||!c.active||x.channelId!==S.ch||x.epoch!==c.active.epoch)return;if(x.type==='offer'&&x.from===c.active.sessionId){if(S.peer)S.peer.close();const pc=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302']}]});S.peer=pc;pc.ontrack=e=>$('audio').srcObject=e.streams[0];await pc.setRemoteDescription(x.payload.sdp);const a=await pc.createAnswer();await pc.setLocalDescription(a);await gather(pc);await api('POST','signal',{sessionId:S.id,to:x.from,type:'answer',channelId:S.ch,epoch:x.epoch,payload:{sdp:pc.localDescription}})}else if(x.type==='answer'&&S.speaking){const pc=S.peers.get(x.from);if(pc)await pc.setRemoteDescription(x.payload.sdp)}}
async function pollSignals(){try{const r=await api('GET','signals',{sessionId:S.id});for(const x of r.signals)await handleSignal(x)}catch{}}
function gather(pc){return new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();const to=setTimeout(resolve,4500),f=()=>{if(pc.iceGatheringState==='complete'){clearTimeout(to);pc.removeEventListener('icegatheringstatechange',f);resolve()}};pc.addEventListener('icegatheringstatechange',f)})}
$('role').onchange=()=>$('codeWrap').classList.toggle('hide',$('role').value!=='admin');
$('joinForm').onsubmit=async e=>{e.preventDefault();S.name=$('name').value.trim();S.role=$('role').value;S.adminCode=$('code').value.trim();if(!S.name)return;await askNotif();await micPermission();try{await join()}catch(x){toast(x.data&&x.data.error?x.data.error:x.message)}};
$('ptt').onpointerdown=e=>{e.preventDefault();$('ptt').setPointerCapture&&$('ptt').setPointerCapture(e.pointerId);startTalk()};$('ptt').onpointerup=e=>{e.preventDefault();stopTalk()};$('ptt').onpointercancel=()=>stopTalk();$('ptt').oncontextmenu=e=>e.preventDefault();
$('request').onclick=async()=>{try{await api('POST','request',{sessionId:S.id});S.requested=true;await load();toast('İstek sıraya alındı.')}catch(e){toast(e.message)}};
$('newChannel').onclick=async()=>{const n=prompt('Yeni kanal adı');if(!n)return;try{await api('POST','createChannel',{sessionId:S.id,name:n});await load()}catch(e){toast(e.message)}};
$('deleteChannel').onclick=async()=>{if(S.ch==='main'||!confirm('Kanal silinsin mi?'))return;try{await api('POST','deleteChannel',{sessionId:S.id,channelId:S.ch});S.ch='main';await join()}catch(e){toast(e.message)}};
$('settings').onclick=()=>$('drawer').classList.remove('hide');$('close').onclick=()=>$('drawer').classList.add('hide');$('askNotif').onclick=askNotif;$('leave').onclick=()=>location.reload();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});$('display').textContent=matchMedia('(display-mode: standalone)').matches?'Kurulu PWA':'Tarayıcı';addEventListener('keydown',e=>{if(['Space','Enter'].includes(e.code)&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='SELECT'){e.preventDefault();startTalk()}});addEventListener('keyup',e=>{if(['Space','Enter'].includes(e.code))stopTalk()});addEventListener('beforeunload',()=>{if(S.stream)S.stream.getTracks().forEach(t=>t.stop())});addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.deferred=e;$('install').classList.remove('hide')});$('install').onclick=async()=>{if(S.deferred){await S.deferred.prompt();S.deferred=null;$('install').classList.add('hide')}};
